name: challenge_bloc
description: Challenge app with BLoC
version: 2.0.1+7
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.2
  equatable: ^2.0.5
  firebase_analytics: ^10.6.1
  firebase_core: ^2.7.1
  firebase_dynamic_links: ^5.3.7
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  supabase_flutter: ^2.0.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/
    - assets/recetas/
    - assets/images/

  # Fonts
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
          weight: 200
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
